<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/app.php';
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Vote Online — VoteHub</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
<link href="<?=htmlspecialchars(APP_URL,ENT_QUOTES)?>/assets/css/app.css" rel="stylesheet">
<style>
body{background:#f5f7fb}.vote-shell{max-width:1180px;margin:0 auto;padding:32px 16px}.vote-brand{display:flex;align-items:center;gap:12px}.vote-brand .icon{width:46px;height:46px;border-radius:14px;display:grid;place-items:center;background:#0f6b2e;color:#fff;font-size:22px}.hero{background:linear-gradient(135deg,#0b4f22,#0f6b2e);color:#fff;border-radius:24px;padding:34px;margin-bottom:24px}.hero h1{font-weight:800}.cardx{background:#fff;border:1px solid #e7ebf0;border-radius:18px;box-shadow:0 10px 30px rgba(16,24,40,.06)}.contestant{cursor:pointer;border:2px solid transparent;border-radius:16px;padding:14px;height:100%;transition:.18s}.contestant:hover{transform:translateY(-2px);box-shadow:0 8px 24px rgba(0,0,0,.08)}.contestant.selected{border-color:#f4c430;background:#fffdf1}.photo{width:74px;height:74px;border-radius:16px;object-fit:cover;background:#e9eef1;display:grid;place-items:center;font-weight:800;color:#0f6b2e}.code{font-family:monospace;background:#eef7f0;color:#0b4f22;padding:3px 7px;border-radius:7px}.price{font-weight:800;color:#0f6b2e}.sticky{position:sticky;top:20px}.step{width:30px;height:30px;border-radius:50%;display:grid;place-items:center;background:#0f6b2e;color:#fff;font-weight:700}.small-muted{font-size:.86rem;color:#6b7280}.success-box{background:#eefbf1;border:1px solid #b7e3c0;border-radius:14px;padding:18px}.pending-box{background:#fff8e5;border:1px solid #f4d98b;border-radius:14px;padding:18px}.error-box{background:#fff0f0;border:1px solid #f1b4b4;border-radius:14px;padding:18px}
</style>
</head>
<body>
<div class="vote-shell">
<header class="d-flex justify-content-between align-items-center mb-4"><div class="vote-brand"><div class="icon"><i class="bi bi-broadcast-pin"></i></div><div><strong class="fs-5">VoteHub</strong><div class="small-muted">Secure online voting</div></div></div><a href="<?=htmlspecialchars(APP_URL,ENT_QUOTES)?>/" class="btn btn-outline-secondary btn-sm">Home</a></header>
<section class="hero"><div class="row align-items-center"><div class="col-lg-8"><div class="small text-uppercase opacity-75 fw-bold mb-2">Official Voting Portal</div><h1>Vote for your favourite contestant</h1><p class="mb-0 opacity-75">Select an event, choose a category and contestant, then complete mobile-money payment. Votes are counted only after successful payment confirmation.</p></div><div class="col-lg-4 text-lg-end mt-3 mt-lg-0"><span class="badge bg-light text-dark p-2"><i class="bi bi-shield-check me-1"></i>Payment protected</span></div></div></section>
<div id="alert"></div>
<div class="row g-4"><div class="col-lg-8"><div class="cardx p-4 mb-4"><div class="d-flex gap-3 mb-4"><span class="step">1</span><div><h5 class="mb-1">Choose event</h5><div class="small-muted">Only active events accepting votes are shown.</div></div></div><select id="event" class="form-select form-select-lg"><option value="">Loading events…</option></select></div>
<div class="cardx p-4 mb-4"><div class="d-flex gap-3 mb-4"><span class="step">2</span><div><h5 class="mb-1">Choose category</h5><div class="small-muted">Vote price can differ by category.</div></div></div><select id="category" class="form-select form-select-lg" disabled><option value="">Select an event first</option></select></div>
<div class="cardx p-4"><div class="d-flex gap-3 mb-4"><span class="step">3</span><div><h5 class="mb-1">Choose contestant</h5><div class="small-muted">Select the contestant you want to support.</div></div></div><div id="contestants" class="row g-3"><div class="col-12 small-muted">Select an event and category.</div></div></div></div>
<div class="col-lg-4"><div class="cardx p-4 sticky"><div class="d-flex gap-3 mb-4"><span class="step">4</span><div><h5 class="mb-1">Complete vote</h5><div class="small-muted">Payment is required before votes are recorded.</div></div></div><div id="selectedBox" class="border rounded-3 p-3 mb-3 bg-light"><div class="small-muted">No contestant selected.</div></div><label class="form-label">Number of votes</label><input id="votes" type="number" min="1" value="1" class="form-control form-control-lg mb-3"><label class="form-label">Mobile number</label><input id="phone" type="tel" class="form-control form-control-lg mb-3" placeholder="024XXXXXXX"><label class="form-label">Email</label><input id="email" type="email" class="form-control mb-3" placeholder="voter@example.com"><label class="form-label">Mobile money network</label><select id="provider" class="form-select form-select-lg mb-3"><option value="mtn">MTN</option><option value="vod">Telecel</option><option value="atl">AT</option></select><div class="d-flex justify-content-between border-top pt-3 mb-3"><span>Total</span><strong id="total">GHS 0.00</strong></div><button id="pay" class="btn btn-success btn-lg w-100" disabled><i class="bi bi-phone me-1"></i>Pay & Submit Vote</button><div class="small-muted mt-3">By continuing, you confirm the selected contestant and authorize the mobile-money payment. A vote is recorded only when Paystack confirms success.</div><div id="paymentStatus" class="mt-3"></div></div></div></div>
</div>
<script>
const API='../api/';let data={events:[],categories:[],contestants:[]},selected=null,lastRef='';
const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat('en-GH',{style:'currency',currency:'GHS'}).format(Number(n)||0);
function alertBox(msg,type='danger'){ $('alert').innerHTML=`<div class="alert alert-${type} alert-dismissible fade show" role="alert">${msg}<button class="btn-close" data-bs-dismiss="alert"></button></div>`;window.scrollTo({top:0,behavior:'smooth'}); }
async function load(){try{const r=await fetch(API+'public_voting_options.php',{headers:{Accept:'application/json'}});const j=await r.json();if(!j.success)throw Error(j.message);data=j; $('event').innerHTML='<option value="">Select an event</option>'+data.events.map(e=>`<option value="${e.id}">${esc(e.name)} — ${esc(e.event_code)}</option>`).join('');}catch(e){alertBox('Unable to load the voting catalogue. Please try again later.');}}
function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));}
$('event').addEventListener('change',()=>{const id=$('event').value;$('category').disabled=!id;$('category').innerHTML='<option value="">Select a category</option>'+data.categories.filter(c=>String(c.event_id)===String(id)).map(c=>`<option value="${c.id}">${esc(c.name)} — ${esc(c.category_code)} (${money(c.vote_price)}/vote)</option>`).join('');$('contestants').innerHTML='<div class="col-12 small-muted">Select a category.</div>';selected=null;update();});
$('category').addEventListener('change',renderContestants);$('votes').addEventListener('input',update);$('phone').addEventListener('input',update);$('email').addEventListener('input',update);
function renderContestants(){const cid=$('category').value;const list=data.contestants.filter(c=>String(c.category_id)===String(cid)&&String(c.event_id)===String($('event').value));$('contestants').innerHTML=list.length?list.map(c=>`<div class="col-md-6"><div class="contestant" data-id="${c.id}"><div class="d-flex gap-3 align-items-center"><div class="photo">${c.photo?`<img src="../${esc(c.photo)}" class="photo" alt="">`:esc(c.full_name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase())}</div><div><strong>${esc(c.full_name)}</strong><div class="small-muted mt-1">Code <span class="code">${esc(c.contestant_code)}</span></div><div class="price mt-1">${money(c.vote_price)} per vote</div></div></div></div></div>`).join(''):'<div class="col-12 small-muted">No active contestants in this category.</div>';document.querySelectorAll('.contestant').forEach(el=>el.addEventListener('click',()=>{document.querySelectorAll('.contestant').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');selected=data.contestants.find(c=>String(c.id)===String(el.dataset.id));update();}));}
function update(){if(!selected){$('selectedBox').innerHTML='<div class="small-muted">No contestant selected.</div>';$('total').textContent=money(0);$('pay').disabled=true;return;}const n=Math.max(1,parseInt($('votes').value||'1',10));$('votes').value=n;$('selectedBox').innerHTML=`<strong>${esc(selected.full_name)}</strong><div class="small-muted">${esc(selected.category_name)} · Code ${esc(selected.contestant_code)}</div>`;$('total').textContent=money(Number(selected.vote_price)*n);const max=Number(selected.max_votes_per_transaction||20);$('pay').disabled=!$('phone').value.trim()||!$('email').value.trim()||n<1||n>max;}
$('pay').addEventListener('click',async()=>{if(!selected)return;const n=parseInt($('votes').value,10);$('pay').disabled=true;$('paymentStatus').innerHTML='<div class="pending-box"><i class="bi bi-hourglass-split me-1"></i>Starting payment. Please authorize the mobile-money prompt on your phone.</div>';try{const fd=new FormData();fd.append('event_id',$('event').value);fd.append('contestant_code',selected.contestant_code);fd.append('vote_count',n);fd.append('phone_number',$('phone').value.trim());fd.append('provider',$('provider').value);fd.append('email',$('email').value.trim());const r=await fetch(API+'initiate_vote.php',{method:'POST',body:fd});const j=await r.json();if(!j.success)throw Error(j.message||'Payment could not be started.');lastRef=j.transaction_reference;$('paymentStatus').innerHTML=`<div class="pending-box"><strong>Payment initiated.</strong><div class="small-muted mt-1">Reference: ${esc(lastRef)}</div><div class="mt-2">${esc(j.message||'Authorize the payment on your phone.')}</div></div>`;poll();}catch(e){$('paymentStatus').innerHTML=`<div class="error-box">${esc(e.message)}</div>`;$('pay').disabled=false;}});
async function poll(){let tries=0;const timer=setInterval(async()=>{tries++;try{const fd=new FormData();fd.append('reference',lastRef);const r=await fetch(API+'verify_payment.php',{method:'POST',body:fd});const j=await r.json();if(j.payment_status==='success'&&j.vote_recorded){clearInterval(timer);$('paymentStatus').innerHTML='<div class="success-box"><h6 class="mb-1"><i class="bi bi-check-circle me-1"></i>Vote recorded successfully</h6><div class="small-muted">Your payment was confirmed and your votes have been added.</div></div>';return;}if(['failed','abandoned','reversed'].includes(j.payment_status)){clearInterval(timer);$('paymentStatus').innerHTML=`<div class="error-box">Payment was not successful. <strong>No vote was recorded.</strong><div class="small-muted mt-1">${esc(j.message||'Please try again.')}</div></div>`;$('pay').disabled=false;return;}if(tries>=24){clearInterval(timer);$('paymentStatus').innerHTML='<div class="pending-box">Payment is still pending. Check your phone and try again later. <strong>No vote is recorded until payment succeeds.</strong></div>';$('pay').disabled=false;}}catch(e){if(tries>=24){clearInterval(timer);$('paymentStatus').innerHTML='<div class="error-box">We could not confirm the payment yet. Please check your transaction status before retrying.</div>';$('pay').disabled=false;}}},5000);}
load();
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body></html>
