<?php
require_once __DIR__ . '/../../includes/auth.php'; requireSuperAdmin(); require_once __DIR__ . '/../../includes/functions.php';
$pageTitle='Transactions';require_once __DIR__.'/../../includes/header.php';require_once __DIR__.'/../../includes/sidebar.php';
$stmt=$pdo->query("SELECT t.*,e.name event_name,e.admin_revenue_percentage,c.name category_name,x.full_name contestant_name FROM transactions t JOIN events e ON e.id=t.event_id JOIN categories c ON c.id=t.category_id JOIN contestants x ON x.id=t.contestant_id ORDER BY t.id DESC LIMIT 100");$rows=$stmt->fetchAll();
?>
<main class="main"><?php require_once __DIR__.'/../../includes/topbar.php';?><section class="content"><div class="mb-4"><h1 class="page-title mb-1">Transactions</h1><p class="page-subtitle">Payment transactions will be populated by the USSD/payment gateway.</p></div>
<div class="panel"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Reference</th><th>Event</th><th>Contestant</th><th>Votes</th><th>Amount</th><th>Admin Share</th><th>Client Share</th><th>Status</th></tr></thead><tbody>
<?php foreach($rows as $r): $adminPct=(float)($r['admin_revenue_percentage']??30); $adminAmount=$r['status']==='Successful'?round((float)$r['amount']*$adminPct/100,2):0; $clientAmount=$r['status']==='Successful'?round((float)$r['amount']-$adminAmount,2):0; ?><tr><td><?= e($r['transaction_reference']) ?></td><td><?= e($r['event_name']) ?></td><td><?= e($r['contestant_name']) ?></td><td><?= $r['vote_count'] ?></td><td>GHS <?= number_format($r['amount'],2) ?></td><td>GHS <?= number_format($adminAmount,2) ?></td><td>GHS <?= number_format($clientAmount,2) ?></td><td><?= e($r['status']) ?></td></tr><?php endforeach; if(!$rows): ?><tr><td colspan="8" class="text-center py-5 text-secondary">No transactions yet.</td></tr><?php endif; ?>
</tbody></table></div></div></section></main><?php require_once __DIR__.'/../../includes/footer.php';?>
