<?php
declare(strict_types=1);
require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../config/paystack.php';
require_once __DIR__ . '/../../config/database.php';
requireSuperAdmin();
$d=paystackDiagnostics();
$lastFailed = null;
try {
    $stmt=$pdo->query("SELECT transaction_reference,event_id,contestant_id,phone_number,amount,status,metadata,created_at FROM transactions WHERE status='Failed' ORDER BY id DESC LIMIT 1");
    $lastFailed=$stmt->fetch(PDO::FETCH_ASSOC) ?: null;
} catch(Throwable $e) {}
$failureMeta=[];
if ($lastFailed && !empty($lastFailed['metadata'])) {
    $decoded=json_decode((string)$lastFailed['metadata'],true);
    if(is_array($decoded)) $failureMeta=$decoded;
}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Paystack Diagnostics</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><div class="container py-5"><div class="card shadow-sm"><div class="card-body p-4"><h3>Paystack Diagnostics</h3><p class="text-muted">Safe diagnostic check. The secret key itself is never displayed.</p><div class="row g-3 mt-2"><div class="col-md-6"><strong>Mode</strong><div><?=htmlspecialchars($d['mode'])?></div></div><div class="col-md-6"><strong>Key configured</strong><div><?= $d['key_configured']?'Yes':'No' ?></div></div><div class="col-md-6"><strong>Key type</strong><div><?=htmlspecialchars($d['key_type'])?></div></div><div class="col-md-6"><strong>Mode/key match</strong><div><?= $d['mode_key_match']?'Yes':'No' ?></div></div><div class="col-12"><strong>API connection</strong><div class="mt-1"><span class="badge <?= $d['api']==='ok'?'text-bg-success':'text-bg-danger' ?>"><?=htmlspecialchars($d['api'])?></span></div><div class="alert <?= $d['api']==='ok'?'alert-success':'alert-danger' ?> mt-3 mb-0"><?=htmlspecialchars((string)$d['message'])?></div></div></div>
<div class="card shadow-sm mt-4"><div class="card-body p-4"><h5>Last Failed Payment</h5><p class="text-muted small">Technical details are shown only to Super Admins. Secret keys are never displayed.</p><?php if(!$lastFailed): ?><div class="alert alert-secondary mb-0">No failed payment has been recorded.</div><?php else: ?><div class="row g-3"><div class="col-md-4"><strong>Reference</strong><div><?=htmlspecialchars((string)$lastFailed['transaction_reference'])?></div></div><div class="col-md-4"><strong>Amount</strong><div>GHS <?=number_format((float)$lastFailed['amount'],2)?></div></div><div class="col-md-4"><strong>Time</strong><div><?=htmlspecialchars((string)$lastFailed['created_at'])?></div></div><div class="col-12"><strong>Paystack diagnostic</strong><pre class="bg-dark text-light p-3 rounded mt-2 mb-0" style="white-space:pre-wrap"><?=htmlspecialchars(json_encode($failureMeta['payment_error'] ?? $failureMeta, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></pre></div></div><?php endif; ?></div></div>
<div class="card shadow-sm mt-4"><div class="card-body p-4"><h5>Last Charge Response</h5><p class="text-muted small">This is sanitized diagnostic information. Secret keys and full phone numbers are never shown.</p><?php if(!$lastFailed): ?><div class="alert alert-secondary mb-0">No failed charge response is available yet.</div><?php else: ?><pre class="bg-dark text-light p-3 rounded mb-0" style="white-space:pre-wrap"><?=htmlspecialchars(json_encode(['http'=>$failureMeta['http']??null,'code'=>$failureMeta['code']??null,'paystack_status'=>$failureMeta['paystack_status']??null,'paystack_message'=>$failureMeta['paystack_message']??null,'paystack_data'=>$failureMeta['paystack_data']??null,'request'=>$failureMeta['request']??['provider'=>$failureMeta['provider']??null,'amount'=>$failureMeta['amount']??null,'phone_last4'=>$failureMeta['phone_last4']??null]],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></pre><?php endif; ?></div></div><div class="mt-4"><a class="btn btn-outline-secondary" href="index.php">Back to Settings</a></div></div></div></div></body></html>